name = "fortran_tester"
author = "Pierre de Buyl"
copyright = "Copyright (C) 2015-2020 Pierre de Buyl and contributors"
license = "BSD"
description = "Fortran module to test Fortran programs"
maintainer = "Pierre de Buyl"
homepage = "https://github.com/pdebuyl/fortran_tester"

[library]
source-dir = "src"

[install]
library = true

[build]
auto-executables = false
auto-examples = false
auto-tests = true